GET http://localhost:3333 HTTP/1.1

###

POST http://localhost:3333/prepara-fatura HTTP/1.1
Content-Type: application/json

{
    "f_parceiro": 17,
    "f_data_referencia": "abc",
    "f_tipo_de_faturamento": "parceiro"
}