export type PaginationParams = {
	readonly pageSize: number;
	readonly filterByTk?: string | number;
};

export type Maybe<T> = T | null | undefined;

export type NonEmptyArray<T> = [T, ...T[]];

export type DeepPartial<T> = {
	[P in keyof T]?: T[P] extends object ? DeepPartial<T[P]> : T[P];
};

export type PickRequired<T, K extends keyof T> = T & Required<Pick<T, K>>;

export type OmitAutoGenerated<T> = Omit<
	T,
	"id" | "createdAt" | "updatedAt" | "createdById" | "updatedById"
>;
