export const HTTP_STATUS = {
	OK: 200,
	CREATED: 201,
	NO_CONTENT: 204,
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	FORBIDDEN: 403,
	NOT_FOUND: 404,
	UNPROCESSABLE_ENTITY: 422,
	INTERNAL_SERVER_ERROR: 500,
	BAD_GATEWAY: 502,
} as const;

export const ERROR_CODES = {
	NOT_FOUND: "NOT_FOUND",
	ENTITY_VALIDATION_ERROR: "ENTITY_VALIDATION_ERROR",
	DOCUMENT_VALIDATION_ERROR: "DOCUMENT_VALIDATION_ERROR",
	BUSINESS_RULE_ERROR: "BUSINESS_RULE_ERROR",
	EXTERNAL_API_ERROR: "EXTERNAL_API_ERROR",
	FASTIFY_ERROR: "FASTIFY_ERROR",
	VALIDATION_ERROR: "VALIDATION_ERROR",
	INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;
