/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * NocoBase API documentation
 * OpenAPI spec version: 2.0.0-beta.6
 */
import * as zod from "zod";

/**
 * @summary Returns a list of the collection
 */
export const GetTNfcomCobrancaslistQueryParams = zod.object({
	page: zod.number().optional().describe("page number"),
	pageSize: zod.number().optional().describe("page size"),
	sort: zod
		.union([zod.array(zod.string()), zod.string()])
		.optional()
		.describe("sort items by fields, example: `-field1,-field2,field3`"),
	fields: zod
		.union([zod.array(zod.string()), zod.string()])
		.optional()
		.describe("select fields, example: `field1,field2`"),
	appends: zod
		.union([zod.array(zod.string()), zod.string()])
		.optional()
		.describe("append associations in results, example: `assoc1,assoc2`"),
	except: zod
		.union([zod.array(zod.string()), zod.string()])
		.optional()
		.describe("except fields in results, example: `field1,field2`"),
});

export const GetTNfcomCobrancaslistResponse = zod.object({
	data: zod.array(zod.unknown()).optional(),
	meta: zod
		.object({
			count: zod.number().optional().describe("total count"),
			page: zod.number().optional().describe("current page"),
			pageSize: zod.number().optional().describe("items count per page"),
			totalPage: zod.number().optional().describe("total page"),
		})
		.optional(),
});

/**
 * @summary Return a record
 */
export const GetTNfcomCobrancasgetQueryParams = zod.object({
	filterByTk: zod.number().optional().describe("filter by TK(default by ID)"),
	sort: zod
		.union([zod.array(zod.string()), zod.string()])
		.optional()
		.describe("sort items by fields, example: `-field1,-field2,field3`"),
	fields: zod
		.union([zod.array(zod.string()), zod.string()])
		.optional()
		.describe("select fields, example: `field1,field2`"),
	appends: zod
		.union([zod.array(zod.string()), zod.string()])
		.optional()
		.describe("append associations in results, example: `assoc1,assoc2`"),
	except: zod
		.union([zod.array(zod.string()), zod.string()])
		.optional()
		.describe("except fields in results, example: `field1,field2`"),
});

export const GetTNfcomCobrancasgetResponse = zod.object({
	data: zod.unknown().optional(),
});

/**
 * @summary Create record
 */
export const PostTNfcomCobrancascreateQueryParams = zod.object({
	whitelist: zod
		.union([zod.array(zod.string()), zod.string()])
		.optional()
		.describe("whitelist for fields changes, example: `field1,field2`"),
	blacklist: zod
		.union([zod.array(zod.string()), zod.string()])
		.optional()
		.describe("blacklist for fields changes, example: `field1,field2`"),
});

export const PostTNfcomCobrancascreateBody = zod.unknown();

export const PostTNfcomCobrancascreateResponse = zod.object({
	data: zod.unknown().optional(),
});

/**
 * @summary Update record
 */
export const PostTNfcomCobrancasupdateQueryParams = zod.object({
	filterByTk: zod.number().optional().describe("filter by TK(default by ID)"),
	whitelist: zod
		.union([zod.array(zod.string()), zod.string()])
		.optional()
		.describe("whitelist for fields changes, example: `field1,field2`"),
	blacklist: zod
		.union([zod.array(zod.string()), zod.string()])
		.optional()
		.describe("blacklist for fields changes, example: `field1,field2`"),
});

export const PostTNfcomCobrancasupdateBody = zod.unknown();

export const PostTNfcomCobrancasupdateResponse = zod.object({
	data: zod.unknown().optional(),
});

/**
 * @summary Delete record
 */
export const PostTNfcomCobrancasdestroyQueryParams = zod.object({
	filterByTk: zod.number().optional().describe("filter by TK(default by ID)"),
});

/**
 * @summary Return a list of One to many relationship
 */
export const GetTNfcomCobrancasCollectionIndexFNotasFiscaislistParams =
	zod.object({
		collectionIndex: zod.number().describe("collection index"),
	});

export const GetTNfcomCobrancasCollectionIndexFNotasFiscaislistQueryParams =
	zod.object({
		page: zod.number().optional().describe("page number"),
		pageSize: zod.number().optional().describe("page size"),
		sort: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("sort items by fields, example: `-field1,-field2,field3`"),
		fields: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("select fields, example: `field1,field2`"),
		appends: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("append associations in results, example: `assoc1,assoc2`"),
		except: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("except fields in results, example: `field1,field2`"),
	});

export const GetTNfcomCobrancasCollectionIndexFNotasFiscaislistResponse =
	zod.object({
		data: zod.array(zod.unknown()).optional(),
		meta: zod
			.object({
				count: zod.number().optional().describe("total count"),
				page: zod.number().optional().describe("current page"),
				pageSize: zod.number().optional().describe("items count per page"),
				totalPage: zod.number().optional().describe("total page"),
			})
			.optional(),
	});

/**
 * @summary Return a record of One to many
 */
export const GetTNfcomCobrancasCollectionIndexFNotasFiscaisgetParams =
	zod.object({
		collectionIndex: zod.number().describe("collection index"),
	});

export const GetTNfcomCobrancasCollectionIndexFNotasFiscaisgetQueryParams =
	zod.object({
		filterByTk: zod.number().optional().describe("filter by TK(default by ID)"),
		sort: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("sort items by fields, example: `-field1,-field2,field3`"),
		fields: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("select fields, example: `field1,field2`"),
		appends: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("append associations in results, example: `assoc1,assoc2`"),
		except: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("except fields in results, example: `field1,field2`"),
	});

export const GetTNfcomCobrancasCollectionIndexFNotasFiscaisgetResponse =
	zod.object({
		data: zod.unknown().optional(),
	});

/**
 * @summary Create and associate a record
 */
export const PostTNfcomCobrancasCollectionIndexFNotasFiscaiscreateParams =
	zod.object({
		collectionIndex: zod.number().describe("collection index"),
	});

export const PostTNfcomCobrancasCollectionIndexFNotasFiscaiscreateQueryParams =
	zod.object({
		whitelist: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("whitelist for fields changes, example: `field1,field2`"),
		blacklist: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("blacklist for fields changes, example: `field1,field2`"),
	});

export const PostTNfcomCobrancasCollectionIndexFNotasFiscaiscreateBody =
	zod.unknown();

export const PostTNfcomCobrancasCollectionIndexFNotasFiscaiscreateResponse =
	zod.object({
		data: zod.unknown().optional(),
	});

/**
 * @summary Update the relationship record
 */
export const PostTNfcomCobrancasCollectionIndexFNotasFiscaisupdateParams =
	zod.object({
		collectionIndex: zod.number().describe("collection index"),
	});

export const PostTNfcomCobrancasCollectionIndexFNotasFiscaisupdateQueryParams =
	zod.object({
		filterByTk: zod.number().optional().describe("filter by TK(default by ID)"),
		whitelist: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("whitelist for fields changes, example: `field1,field2`"),
		blacklist: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("blacklist for fields changes, example: `field1,field2`"),
	});

export const PostTNfcomCobrancasCollectionIndexFNotasFiscaisupdateBody =
	zod.unknown();

export const PostTNfcomCobrancasCollectionIndexFNotasFiscaisupdateResponse =
	zod.object({
		data: zod.unknown().optional(),
	});

/**
 * @summary Destroy and disassociate the relationship record
 */
export const PostTNfcomCobrancasCollectionIndexFNotasFiscaisdestroyParams =
	zod.object({
		collectionIndex: zod.number().describe("collection index"),
	});

export const PostTNfcomCobrancasCollectionIndexFNotasFiscaisdestroyQueryParams =
	zod.object({
		filterByTk: zod.number().optional().describe("filter by TK(default by ID)"),
	});

/**
 * @summary Set or reset associations
 */
export const PostTNfcomCobrancasCollectionIndexFNotasFiscaissetParams =
	zod.object({
		collectionIndex: zod.number().describe("collection index"),
	});

export const PostTNfcomCobrancasCollectionIndexFNotasFiscaissetQueryParams =
	zod.object({
		filterByTk: zod
			.array(zod.number())
			.optional()
			.describe("filter by TKs(default by ID), example: `1,2,3`"),
	});

/**
 * @summary Detach record
 */
export const PostTNfcomCobrancasCollectionIndexFNotasFiscaisremoveParams =
	zod.object({
		collectionIndex: zod.number().describe("collection index"),
	});

export const PostTNfcomCobrancasCollectionIndexFNotasFiscaisremoveQueryParams =
	zod.object({
		filterByTk: zod
			.array(zod.number())
			.optional()
			.describe("filter by TKs(default by ID), example: `1,2,3`"),
	});

/**
 * @summary Attach or detach record
 */
export const PostTNfcomCobrancasCollectionIndexFNotasFiscaistoggleParams =
	zod.object({
		collectionIndex: zod.number().describe("collection index"),
	});

export const PostTNfcomCobrancasCollectionIndexFNotasFiscaistoggleQueryParams =
	zod.object({
		filterByTk: zod.number().optional().describe("filter by TK(default by ID)"),
	});

/**
 * @summary Return a record of Many to one
 */
export const GetTNfcomCobrancasCollectionIndexFFaturagetParams = zod.object({
	collectionIndex: zod.number().describe("collection index"),
});

export const GetTNfcomCobrancasCollectionIndexFFaturagetQueryParams =
	zod.object({
		fields: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("select fields, example: `field1,field2`"),
		appends: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("append associations in results, example: `assoc1,assoc2`"),
		except: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("except fields in results, example: `field1,field2`"),
	});

export const GetTNfcomCobrancasCollectionIndexFFaturagetResponse = zod.object({
	data: zod.unknown().optional(),
});

/**
 * @summary Associate a record
 */
export const PostTNfcomCobrancasCollectionIndexFFaturasetParams = zod.object({
	collectionIndex: zod.number().describe("collection index"),
});

export const PostTNfcomCobrancasCollectionIndexFFaturasetQueryParams =
	zod.object({
		tk: zod.string().optional().describe("targetKey"),
	});

/**
 * @summary Disassociate the relationship record
 */
export const PostTNfcomCobrancasCollectionIndexFFaturaremoveParams = zod.object(
	{
		collectionIndex: zod.number().describe("collection index"),
	},
);

/**
 * @summary Update the relationship record
 */
export const PostTNfcomCobrancasCollectionIndexFFaturaupdateParams = zod.object(
	{
		collectionIndex: zod.number().describe("collection index"),
	},
);

export const PostTNfcomCobrancasCollectionIndexFFaturaupdateQueryParams =
	zod.object({
		whitelist: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("whitelist for fields changes, example: `field1,field2`"),
		blacklist: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("blacklist for fields changes, example: `field1,field2`"),
	});

export const PostTNfcomCobrancasCollectionIndexFFaturaupdateBody =
	zod.unknown();

export const PostTNfcomCobrancasCollectionIndexFFaturaupdateResponse =
	zod.object({
		data: zod.unknown().optional(),
	});

/**
 * @summary Create and associate a record
 */
export const PostTNfcomCobrancasCollectionIndexFFaturacreateParams = zod.object(
	{
		collectionIndex: zod.number().describe("collection index"),
	},
);

export const PostTNfcomCobrancasCollectionIndexFFaturacreateQueryParams =
	zod.object({
		whitelist: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("whitelist for fields changes, example: `field1,field2`"),
		blacklist: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("blacklist for fields changes, example: `field1,field2`"),
	});

export const PostTNfcomCobrancasCollectionIndexFFaturacreateBody =
	zod.unknown();

export const PostTNfcomCobrancasCollectionIndexFFaturacreateResponse =
	zod.object({
		data: zod.unknown().optional(),
	});

/**
 * @summary Destroy and disassociate the relationship record
 */
export const PostTNfcomCobrancasCollectionIndexFFaturadestroyParams =
	zod.object({
		collectionIndex: zod.number().describe("collection index"),
	});

/**
 * @summary Return a list of One to many relationship
 */
export const GetTNfcomCobrancasCollectionIndexFItensAdicionaislistParams =
	zod.object({
		collectionIndex: zod.number().describe("collection index"),
	});

export const GetTNfcomCobrancasCollectionIndexFItensAdicionaislistQueryParams =
	zod.object({
		page: zod.number().optional().describe("page number"),
		pageSize: zod.number().optional().describe("page size"),
		sort: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("sort items by fields, example: `-field1,-field2,field3`"),
		fields: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("select fields, example: `field1,field2`"),
		appends: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("append associations in results, example: `assoc1,assoc2`"),
		except: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("except fields in results, example: `field1,field2`"),
	});

export const GetTNfcomCobrancasCollectionIndexFItensAdicionaislistResponse =
	zod.object({
		data: zod.array(zod.unknown()).optional(),
		meta: zod
			.object({
				count: zod.number().optional().describe("total count"),
				page: zod.number().optional().describe("current page"),
				pageSize: zod.number().optional().describe("items count per page"),
				totalPage: zod.number().optional().describe("total page"),
			})
			.optional(),
	});

/**
 * @summary Return a record of One to many
 */
export const GetTNfcomCobrancasCollectionIndexFItensAdicionaisgetParams =
	zod.object({
		collectionIndex: zod.number().describe("collection index"),
	});

export const GetTNfcomCobrancasCollectionIndexFItensAdicionaisgetQueryParams =
	zod.object({
		filterByTk: zod.number().optional().describe("filter by TK(default by ID)"),
		sort: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("sort items by fields, example: `-field1,-field2,field3`"),
		fields: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("select fields, example: `field1,field2`"),
		appends: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("append associations in results, example: `assoc1,assoc2`"),
		except: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("except fields in results, example: `field1,field2`"),
	});

export const GetTNfcomCobrancasCollectionIndexFItensAdicionaisgetResponse =
	zod.object({
		data: zod.unknown().optional(),
	});

/**
 * @summary Create and associate a record
 */
export const PostTNfcomCobrancasCollectionIndexFItensAdicionaiscreateParams =
	zod.object({
		collectionIndex: zod.number().describe("collection index"),
	});

export const PostTNfcomCobrancasCollectionIndexFItensAdicionaiscreateQueryParams =
	zod.object({
		whitelist: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("whitelist for fields changes, example: `field1,field2`"),
		blacklist: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("blacklist for fields changes, example: `field1,field2`"),
	});

export const PostTNfcomCobrancasCollectionIndexFItensAdicionaiscreateBody =
	zod.unknown();

export const PostTNfcomCobrancasCollectionIndexFItensAdicionaiscreateResponse =
	zod.object({
		data: zod.unknown().optional(),
	});

/**
 * @summary Update the relationship record
 */
export const PostTNfcomCobrancasCollectionIndexFItensAdicionaisupdateParams =
	zod.object({
		collectionIndex: zod.number().describe("collection index"),
	});

export const PostTNfcomCobrancasCollectionIndexFItensAdicionaisupdateQueryParams =
	zod.object({
		filterByTk: zod.number().optional().describe("filter by TK(default by ID)"),
		whitelist: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("whitelist for fields changes, example: `field1,field2`"),
		blacklist: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("blacklist for fields changes, example: `field1,field2`"),
	});

export const PostTNfcomCobrancasCollectionIndexFItensAdicionaisupdateBody =
	zod.unknown();

export const PostTNfcomCobrancasCollectionIndexFItensAdicionaisupdateResponse =
	zod.object({
		data: zod.unknown().optional(),
	});

/**
 * @summary Destroy and disassociate the relationship record
 */
export const PostTNfcomCobrancasCollectionIndexFItensAdicionaisdestroyParams =
	zod.object({
		collectionIndex: zod.number().describe("collection index"),
	});

export const PostTNfcomCobrancasCollectionIndexFItensAdicionaisdestroyQueryParams =
	zod.object({
		filterByTk: zod.number().optional().describe("filter by TK(default by ID)"),
	});

/**
 * @summary Set or reset associations
 */
export const PostTNfcomCobrancasCollectionIndexFItensAdicionaissetParams =
	zod.object({
		collectionIndex: zod.number().describe("collection index"),
	});

export const PostTNfcomCobrancasCollectionIndexFItensAdicionaissetQueryParams =
	zod.object({
		filterByTk: zod
			.array(zod.number())
			.optional()
			.describe("filter by TKs(default by ID), example: `1,2,3`"),
	});

/**
 * @summary Detach record
 */
export const PostTNfcomCobrancasCollectionIndexFItensAdicionaisremoveParams =
	zod.object({
		collectionIndex: zod.number().describe("collection index"),
	});

export const PostTNfcomCobrancasCollectionIndexFItensAdicionaisremoveQueryParams =
	zod.object({
		filterByTk: zod
			.array(zod.number())
			.optional()
			.describe("filter by TKs(default by ID), example: `1,2,3`"),
	});

/**
 * @summary Attach or detach record
 */
export const PostTNfcomCobrancasCollectionIndexFItensAdicionaistoggleParams =
	zod.object({
		collectionIndex: zod.number().describe("collection index"),
	});

export const PostTNfcomCobrancasCollectionIndexFItensAdicionaistoggleQueryParams =
	zod.object({
		filterByTk: zod.number().optional().describe("filter by TK(default by ID)"),
	});

/**
 * @summary Return a record of One to one
 */
export const GetTNfcomCobrancasCollectionIndexFErrogetParams = zod.object({
	collectionIndex: zod.number().describe("collection index"),
});

export const GetTNfcomCobrancasCollectionIndexFErrogetQueryParams = zod.object({
	fields: zod
		.union([zod.array(zod.string()), zod.string()])
		.optional()
		.describe("select fields, example: `field1,field2`"),
	appends: zod
		.union([zod.array(zod.string()), zod.string()])
		.optional()
		.describe("append associations in results, example: `assoc1,assoc2`"),
	except: zod
		.union([zod.array(zod.string()), zod.string()])
		.optional()
		.describe("except fields in results, example: `field1,field2`"),
});

export const GetTNfcomCobrancasCollectionIndexFErrogetResponse = zod.object({
	data: zod.unknown().optional(),
});

/**
 * @summary Associate a record
 */
export const PostTNfcomCobrancasCollectionIndexFErrosetParams = zod.object({
	collectionIndex: zod.number().describe("collection index"),
});

export const PostTNfcomCobrancasCollectionIndexFErrosetQueryParams = zod.object(
	{
		tk: zod.string().optional().describe("targetKey"),
	},
);

/**
 * @summary Disassociate the relationship record
 */
export const PostTNfcomCobrancasCollectionIndexFErroremoveParams = zod.object({
	collectionIndex: zod.number().describe("collection index"),
});

/**
 * @summary Update the relationship record
 */
export const PostTNfcomCobrancasCollectionIndexFErroupdateParams = zod.object({
	collectionIndex: zod.number().describe("collection index"),
});

export const PostTNfcomCobrancasCollectionIndexFErroupdateQueryParams =
	zod.object({
		whitelist: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("whitelist for fields changes, example: `field1,field2`"),
		blacklist: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("blacklist for fields changes, example: `field1,field2`"),
	});

export const PostTNfcomCobrancasCollectionIndexFErroupdateBody = zod.unknown();

export const PostTNfcomCobrancasCollectionIndexFErroupdateResponse = zod.object(
	{
		data: zod.unknown().optional(),
	},
);

/**
 * @summary Create and associate a record
 */
export const PostTNfcomCobrancasCollectionIndexFErrocreateParams = zod.object({
	collectionIndex: zod.number().describe("collection index"),
});

export const PostTNfcomCobrancasCollectionIndexFErrocreateQueryParams =
	zod.object({
		whitelist: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("whitelist for fields changes, example: `field1,field2`"),
		blacklist: zod
			.union([zod.array(zod.string()), zod.string()])
			.optional()
			.describe("blacklist for fields changes, example: `field1,field2`"),
	});

export const PostTNfcomCobrancasCollectionIndexFErrocreateBody = zod.unknown();

export const PostTNfcomCobrancasCollectionIndexFErrocreateResponse = zod.object(
	{
		data: zod.unknown().optional(),
	},
);

/**
 * @summary Destroy and disassociate the relationship record
 */
export const PostTNfcomCobrancasCollectionIndexFErrodestroyParams = zod.object({
	collectionIndex: zod.number().describe("collection index"),
});
