import type { Cliente } from "@/@types/atacado/Cliente";
import type { Cobranca } from "@/@types/atacado/Cobranca";
import type { Fatura } from "@/@types/atacado/Fatura";
import type { ItemNFCom } from "@/@types/atacado/ItemNFCom";
import type { NFCom } from "@/@types/atacado/NFCom";
import type { Parceiro } from "@/@types/atacado/Parceiro";
import type { PlanoDeServico } from "@/@types/atacado/PlanoDeServico";
import type {
	AtacadoRepository,
	ClientsFilter,
	OmitAutoGenerated,
} from "@/modules/atacado/wholesale.repository.types";
import { NotFoundError } from "@/shared/base.error";
import {
	ATACADO_ROUTES,
	atacadoHttpClient,
} from "./http-client/atacado-http-client";
import { PAGINATION } from "./wholesale.constants";

class AtacadoApiRepository implements AtacadoRepository {
	async findParceiroById(id: string | number): Promise<Parceiro> {
		const response = await atacadoHttpClient.get<Parceiro>(
			`${ATACADO_ROUTES.parceiros}:get`,
			{ params: { filterByTk: id } },
		);

		if (!response.data) {
			throw NotFoundError.create("Parceiro", id);
		}

		return response.data;
	}

	async findClientesAtivosByParceiroId(
		filter: ClientsFilter,
	): Promise<readonly Cliente[]> {
		const { partnerId, activeLineStatus = true } = filter;

		const response = await atacadoHttpClient.get<Cliente[]>(
			`${ATACADO_ROUTES.clientes}:list`,
			{
				params: {
					filterByTk: partnerId,
					pageSize: PAGINATION.DEFAULT_PAGE_SIZE,
					...(activeLineStatus && {
						filter: {
							f_fk_parceiro: partnerId,
							"f_linhas_fixas.f_status": { $eq: 1 },
						},
						appends: ["f_linhas_fixas"],
					}),
				},
			},
		);

		return response.data ?? [];
	}

	async findAllPlanosDeServico(): Promise<readonly PlanoDeServico[]> {
		const response = await atacadoHttpClient.get<PlanoDeServico[]>(
			`${ATACADO_ROUTES.planosDeServico}:list`,
			{ params: { pageSize: PAGINATION.DEFAULT_PAGE_SIZE } },
		);

		return response.data ?? [];
	}

	async createFatura(data: OmitAutoGenerated<Fatura>): Promise<Fatura> {
		const response = await atacadoHttpClient.post<Fatura>(
			`${ATACADO_ROUTES.faturas}:create`,
			data,
		);
		return response.data;
	}

	async createCobranca(data: OmitAutoGenerated<Cobranca>): Promise<Cobranca> {
		const response = await atacadoHttpClient.post<Cobranca>(
			`${ATACADO_ROUTES.cobrancas}:create`,
			data,
		);
		return response.data;
	}

	async createNFCom(
		cobrancaId: string | number,
		data: OmitAutoGenerated<NFCom>,
	): Promise<NFCom> {
		const response = await atacadoHttpClient.post<NFCom>(
			`${ATACADO_ROUTES.cobrancas}/${cobrancaId}/f_notas_fiscais:create`,
			data,
		);
		return response.data;
	}

	async createItemNFCom(
		notaFiscalId: string | number,
		data: OmitAutoGenerated<ItemNFCom>,
	): Promise<ItemNFCom> {
		const response = await atacadoHttpClient.post<ItemNFCom>(
			`${ATACADO_ROUTES.notasFiscais}/${notaFiscalId}/f_nota_itens:create`,
			data,
		);
		return response.data;
	}
}

const atacadoRepository: AtacadoRepository = new AtacadoApiRepository();

export { atacadoRepository, type AtacadoRepository, type ClientsFilter };
