name: Tests

on:
  push:
    branches:
      - main
      - staging

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.28.2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm biome format

      - name: Lint
        run: pnpm biome lint

      - name: Check code
        run: pnpm biome check

      - name: Run tests
        run: pnpm test --coverage

      - name: Build
        run: pnpm build
